# Generated by Django 4.2.6 on 2023-11-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login_form',
        ),
    ]
