# Generated by Django 4.2.6 on 2023-11-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_page', '0002_delete_login_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(choices=[('electronics', 'Electronics'), ('bikes', 'Bikes'), ('cars', 'Cars'), ('clothing', 'Clothing')], max_length=200)),
            ],
        ),
    ]
