# Generated by Django 4.2.6 on 2023-11-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='login_page.CartItem', to='login_page.itemmodel'),
        ),
    ]
